{
    "catchAll": {
        "phrases": [
            "Ваша фраза мне не понятна, Сейчас я могу рассказать о наших текущих проектах, показать пример моей работы, или отправить сообщение Дмитрию! Вы просто скажите - давай отправим сообщение Дмитрию. чтобы прекратить общение, скажите - пока.",
            "Сейчас я умею только рассказать о наших текущих проектах, показать пример моей работы,! ",
            "У меня сейчас три навыка, отправить сообщение, показать пример работы или рассказать о текущих проектах. Вы просто скажите - давай отправим сообщение Дмитрию. чтобы прекратить общение, скажите - пока."
        ]
    },
    "fulfillment": {
        "settings": {
            "default": {
                "url": ""
            },
            "channels": []
        },
        "actions": []
    }
}
